import type { IWordModel } from "../../../entities/word/model/types";

export const kwf1: IWordModel[] = [
  {
    headword: "I",
    PoS: "pron",
    IPA: "[aɪ]",
    definitions: ["я"],
    examples: ["*I* am going to the store.    *I* think this is a good idea."],
  },
  {
    headword: "you",
    PoS: "pron",
    IPA: "[ju]",
    definitions: ["ты; вы"],
    examples: ["*You* are my best friend.    Can *you* help me with this?"],
  },
  {
    headword: "the",
    PoS: "article",
    IPA: "[ðə, ði]",
    definitions: ["определённый артикль"],
    examples: ["Please close *the* door.    *The* book on the table is mine."],
  },
  {
    headword: "be",
    PoS: "v",
    IPA: "[bi]",
    definitions: ["быть", "<вспомогательный глагол>"],
    examples: [
      "She *is* a doctor.",
      "They *are* working on the project.    The report *was* written by the intern.",
    ],
  },
  {
    headword: "to",
    PoS: "prep, particle",
    IPA: "[tu, tə]",
    definitions: ["_prep_ к, до", "_particle_ <частица инфинитива>"],
    examples: ["I am going *to* the park.", "I want *to* learn."],
  },
  {
    headword: "a",
    PoS: "article",
    IPA: "[ə, eɪ]",
    definitions: ["неопределённый артикль"],
    examples: ["She has *a* bycicle.    This is *a* great opportunity."],
  },
  {
    headword: "and",
    PoS: "conj",
    IPA: "[ænd]",
    definitions: ["и"],
    examples: ["You *and* I will go.    I want coffee *and* tea."],
  },
  {
    headword: "it",
    PoS: "pron",
    IPA: "[ɪt]",
    definitions: [
      "<неодушевленное местоимение> оно, это",
      "<фиктивное местоимение – не имеет референтного значения; используется для соблюдения грамматической структуры>",
    ],
    examples: [
      "The book is open; please read *it*.",
      "*It* is raining outside.    I don't like *it* when people are rude.",
    ],
  },
  {
    headword: "of",
    PoS: "prep",
    IPA: "[ʌv, əv]",
    definitions: [
      "<родительный падеж;    набор значений вокруг принадлежности>",
      "из <композиция, материал>",
      "от <причина, мотив>",
    ],
    examples: [
      "She is a citizen *of* France.    It's a matter *of* minutes.    The story *of* my life.    The cover *of* the book is blue.",
      "The statue is made *of* bronze.",
      "He smiled *of* relief.    She wept *of* happiness.",
    ],
  },
  {
    headword: "do",
    PoS: "v",
    IPA: "[du]",
    definitions: ["делать", "<вспомогательный глагол>"],
    examples: ["I *do* my homework every day.", "*Do* you like pizza?"],
  },
  {
    headword: "that",
    PoS: "det, pron, conj, adv",
    IPA: "[ðæt]",
    definitions: ["_det_ тот, та, то", "_pron_ который", "_conj_ что (союз)"],
    examples: [
      "I don't like *that* color.",
      "The book *that* you gave me is amazing.",
      "She said *that* she would call later.",
    ],
  },
  {
    headword: "he",
    PoS: "pron",
    IPA: "[hi]",
    definitions: ["он"],
    examples: ["*He* is my brother.    I think *he* forgot his keys."],
  },
  {
    headword: "in",
    PoS: "prep, adv",
    IPA: "[ɪn]",
    definitions: ["_pron_ в, во", "_adv_ в помещении"],
    examples: [
      "The keys are *in* my bag.",
      "She stayed *in* during the storm.",
    ],
  },
  {
    headword: "have",
    PoS: "v",
    IPA: "[hæv]",
    definitions: ["иметь", "<вспомогательный глагол для перфектного аспекта>"],
    examples: [
      "I *have* a meeting at noon.",
      "They *have* finished their project.",
    ],
  },
  {
    headword: "we",
    PoS: "pron",
    IPA: "[wi]",
    definitions: ["мы"],
    examples: ["*We* are going to the movies.    *We* should talk about this."],
  },
  {
    headword: "what",
    PoS: "pron, det",
    IPA: "[wʌt]",
    definitions: ["_pron_ что", "_det_ какой"],
    examples: ["*What* is your name?", "*What* movie do you want to watch?"],
  },
  {
    headword: "this",
    PoS: "pron, det",
    IPA: "[ðɪs]",
    definitions: ["_pron_ это", "_det_ этот, эта, это"],
    examples: ["*This* is my favorite song.", "I love *this* dress."],
  },
  {
    headword: "she",
    PoS: "pron",
    IPA: "[ʃi]",
    definitions: ["она"],
    examples: ["*She* is an excellent teacher.    I think *she* left already."],
  },
  {
    headword: "for",
    PoS: "prep, conj",
    IPA: "[fɔɹ]",
    definitions: [
      "_prep_ для",
      "_prep_ за",
      "_prep_ в течение",
      "_conj_ ибо, потому что",
    ],
    examples: [
      "This gift is *for* you.",
      "He paid *for* the meal.",
      "I've been waiting *for* hours.",
      "The traveler was weary, *for* he had walked many miles since sunrise.    They were quite wealthy, *for* they owned several estates across Europe.",
    ],
  },
  {
    headword: "go",
    PoS: "v, n",
    IPA: "[ɡoʊ]",
    definitions: [
      "_v_ идти, ехать",
      "_v_ становиться",
      "_n_ ход, попытка или усилие сделать что-либо",
    ],
    examples: [
      "Let's *go* to the beach.    She *goes* to Paris every summer.",
      "The sky *went* dark.",
      "Give it a *go*!",
    ],
  },
  {
    headword: "they",
    PoS: "pron",
    IPA: "[ðeɪ]",
    definitions: ["они"],
    examples: ["*They* are arriving soon.    *They* love music."],
  },
  {
    headword: "on",
    PoS: "prep, adv, adj",
    IPA: "[ɑn, ɔn]",
    definitions: [
      "_prep_ на; <разные предлоги>",
      "_adv_ дальше, вдоль, и т.д.",
      "_adj, adv_ активный, работающий, и т.д.",
    ],
    examples: [
      "The book is *on* the table.    The meeting is *on* Monday.",
      "Go *on*–I'm listening.    He rambled *on* for hours.",
      "The lights are *on*.    Turn *on* the light.",
    ],
  },
  {
    headword: "get",
    PoS: "v",
    IPA: "[ɡɛt]",
    definitions: ["получать", "становиться", "добираться"],
    examples: [
      "Did you *get* my email?",
      "It's *getting* cold.",
      "We need to *get* home by 8.",
    ],
  },
  {
    headword: "know",
    PoS: "v, n",
    IPA: "[noʊ]",
    definitions: [
      "_v_ знать",
      "_v_ быть знакомым",
      "*in the know*: в курсе, осведомлен о секретной или инсайдерской информации",
    ],
    examples: [
      "I *know* the answer.",
      "Do you *know* him?",
      "Ask Sarah about the company restructuring; she's always *in the know* about office gossip.",
    ],
  },
  {
    headword: "not",
    PoS: "adv, conj",
    IPA: "[nɑt]",
    definitions: ["_adv, conj_ не"],
    examples: ["I'm *not* ready.    That's *not* what I meant."],
  },
  {
    headword: "with",
    PoS: "prep, adv",
    IPA: "[wɪð, wɪθ]",
    definitions: ["_prep_ с", "_adv_ вместе"],
    examples: [
      "She's working *with* a team.",
      "You going to the store? I'll come *with*.",
    ],
  },
  {
    headword: "no",
    PoS: "interj, det, adv",
    IPA: "[noʊ]",
    definitions: ["_interj_ нет", "_det_ никакой", "_adv_ не"],
    examples: [
      "*No*, I don't want any coffee.",
      "There is *no* reason to panic.",
      "The second half of the game was *no* less exciting than the first.    I'm *no* good at keeping secrets, so please don't tell me!",
    ],
  },
  {
    headword: "but",
    PoS: "conj, prep, adv, n",
    IPA: "[bʌt]",
    definitions: [
      "_conj_ но",
      "_pron_ кроме",
      "_adv_ только, всего лишь",
      '_n_ пример использования слова "но"; возражение или оговорка.',
    ],
    examples: [
      "I like it, *but* I can't afford it.",
      "Everyone *but* him was invited.",
      "We are *but* a small part of the universe.",
      "I don't want to hear any *buts*.    Every proposal came with a *but*.",
    ],
  },
  {
    headword: "yes",
    PoS: "particle, interj, n",
    IPA: "[jɛs]",
    definitions: [
      "_particle_ да",
      "_interj_ <выражает согласие, утверждение, энтузиазм, удивление или признание>",
      "_n_ утвердительный ответ или согласие",
    ],
    examples: [
      "*Yes*, I agree with you.    *Yes*, she's coming too.",
      "*Yes*! We won!",
      "We need a clear *yes* or no from the committee.",
    ],
  },
  {
    headword: "all",
    PoS: "pron, det, adv",
    IPA: "[ɔl]",
    definitions: ["_pron_ всё", "_det_ все", "_adv_ полностью, исключительно"],
    examples: [
      "*All* is forgiven.",
      "*All* the students passed.",
      "He was dressed *all* in black.",
    ],
  },
  {
    headword: "so",
    PoS: "adv, conj",
    IPA: "[soʊ]",
    definitions: [
      "_adv_ так, настолько",
      "_conj_ поэтому",
      "_adv_ таким образом",
    ],
    examples: [
      "I was *so* tired.",
      "It was late, *so* we went home.",
      "The engine hums *so* when it's overheating.",
    ],
  },
  {
    headword: "just",
    PoS: "adv, adj",
    IPA: "[dʒʌst]",
    definitions: ["_adv_ только что", "_adv_ просто", "_adj_ справедливо"],
    examples: [
      "She *just* left.",
      "I *just* wanted to help.",
      "That's not *just*.",
    ],
  },
  {
    headword: "some",
    PoS: "det, pron",
    IPA: "[sʌm]",
    definitions: [
      "_det_ некоторое количество, несколько, немного",
      "_det_ какой-то, некий; какие-то, некие",
      "_pron_ неопределенное количество или число людей/вещей",
    ],
    examples: [
      "I bought *some* apples.    I need *some* help.",
      "*Some* people never learn.",
      "*Some* believe in fate; others don't.    Not all answers are right–only *some*.",
    ],
  },
  {
    headword: "there",
    PoS: "adv, pron",
    IPA: "[ðɛəɹ]",
    definitions: [
      "_adv_ там",
      "_adv_ туда",
      '_pron_ <фиктивное местоимение – используется в конструкциях "there is/are">',
    ],
    examples: [
      "I've been *there* before.",
      "We decided to move *there* last year.",
      "*There* is a book on the table.",
    ],
  },
  {
    headword: "can",
    PoS: "v, n",
    IPA: "[kæn]",
    definitions: [
      "_v_ могу, может и т.д. <не имеет инфинитива>",
      "_v_ умею, умеет и т.д. <не имеет инфинитива>",
      "_n_ жестяная банка",
    ],
    examples: [
      "*Can* you help me?",
      "I *can* swim.",
      "Recycle that soda *can*–it's aluminum!    He kicked the empty *can* down the street.",
    ],
  },
  {
    headword: "at",
    PoS: "prep",
    IPA: "[æt]",
    definitions: [
      "у, в <о месте>",
      "в <о времени>",
      "на, в <указывает на цель>",
    ],
    examples: [
      "I'm *at* home.",
      "The meeting is *at* 3 PM.",
      "He threw a ball *at* the wall.",
    ],
  },
  {
    headword: "think",
    PoS: "v",
    IPA: "[θɪŋk]",
    definitions: ["думать", "считать, полагать"],
    examples: [
      "I need some time to *think* before I answer.",
      "I *think* it will rain.    What do you *think* of her idea?",
    ],
  },
  {
    headword: "as",
    PoS: "prep, conj, adv",
    IPA: "[æz]",
    definitions: [
      "_prep_ как, в качестве (роль, функция)",
      "_conj_ тем же образом или манерой, что",
      "_adv_ + prep в той же мере, как",
      "_conj_ когда, в то же время, пока",
      "_conj_ потому что",
    ],
    examples: [
      "He works *as* a teacher.",
      "*As* you know, I'm busy.",
      "She is *as* tall *as* her brother.",
      "*As* I was leaving, he called.",
      "We decided to stay home, *as* it was raining.",
    ],
  },
  {
    headword: "about",
    PoS: "prep, adv",
    IPA: "[əˈbaʊt]",
    definitions: [
      "_prep_ о(б), на тему чего-либо, относительно",
      "_adv_ примерно",
      "_prep_ в разных местах в / вокруг / повсюду в",
    ],
    examples: [
      "We talked *about* the plan.",
      "It's *about* five miles from here.",
      "He was wandering *about* the neighborhood.",
    ],
  },
  {
    headword: "if",
    PoS: "conj",
    IPA: "[ɪf]",
    definitions: [
      "если",
      "хотя, даже если (выражает уступку)",
      "ли <в косвенном вопросе>",
    ],
    examples: [
      "*If* it rains, we'll stay inside.",
      "He continued, *if* reluctantly.",
      "I don't know *if* he's coming.",
    ],
  },
  {
    headword: "like",
    PoS: "v, prep, conj, adj, n",
    IPA: "[laɪk]",
    definitions: [
      "_v_ находить что-то приятным",
      "_prep_ как",
      "_conj_ подобно",
      "_adj_ такой же, схожий",
      "_n_ то, что нравится",
    ],
    examples: [
      "I *like* this song.",
      "He runs *like* a professional.",
      "Do it *like* I showed you.",
      "They have *like* interests.",
      "Tell me your *likes* and dislikes.",
    ],
  },
  {
    headword: "well",
    PoS: "adv, adj, n, interj",
    IPA: "[wɛl]",
    definitions: [
      "_adv_ хорошо, должным образом",
      "_adj_ здоровый",
      "_n_ колодец; скважина",
      "_interj_ ≈ну <замена длинного высказывания>",
    ],
    examples: [
      "She plays the piano very *well*.",
      "I don't feel *well* today, I have a cold.    I'm feeling *well* today.",
      "They got water from the *well*.",
      "*Well*, let's begin.",
    ],
  },
  {
    headword: "want",
    PoS: "v, n",
    IPA: "[wɑnt]",
    definitions: ["_v_ хотеть", "_n_ нехватка, недостаток"],
    examples: [
      "I *want* a cup of tea.    Do you *want* to go with us?",
      "There is no *want* of talent in this room–only opportunity.",
    ],
  },
  {
    headword: "say",
    PoS: "v, n",
    IPA: "[seɪ]",
    definitions: ["_v_ сказать", "_n_ право голоса"],
    examples: [
      "What did he *say*?    She *said* she was tired.",
      "Everyone should have their *say* in the matter.",
    ],
  },
  {
    headword: "out",
    PoS: "adv, prep, adj, n, v",
    IPA: "[aʊt]",
    definitions: [
      "_adv_ вне, наружу",
      "_prep_ из, наружу через",
      "_adj_ за пределами, не активный в каком то смысле",
      "_n_ выход, способ ухода",
      "_v_ раскрыть что-то скрытое или секретное",
    ],
    examples: [
      "He went *out* for a walk.",
      "She walked *out* the door.",
      "Working weekends is *out* for me.    Hiring anyone this quarter is *out*.",
      "I'm looking for an easy *out* from this commitment.    If the deal falls through, we have a clear *out* written into the agreement.",
      "The investigation *outed* several officials involved in the scheme.",
    ],
  },
  {
    headword: "right",
    PoS: "adj, adv, n, v",
    IPA: "[ɹaɪt]",
    definitions: [
      "_adj_ правильный, верный",
      "_adv_ вправо, справа",
      "_n_ моральное или юридическое право",
      "_adv_ прямо",
      "_v_ исправить, поправить",
    ],
    examples: [
      "That's the *right* answer.",
      "Turn *right* at the next intersection.",
      "Everyone has a *right* to speak.",
      "She came *right* after lunch.",
      "You should *right* the mistake immediately.",
    ],
  },
  {
    headword: "here",
    PoS: "adv, n, interj",
    IPA: "[hɪəɹ]",
    definitions: [
      "_adv_ здесь",
      "_n_ это место",
      "_interj_ <используется для привлечения внимания или предложения чего-то>",
    ],
    examples: [
      "I'm *here* now.    Put the bags *here*.",
      "*Let's get out of *here*.    From *here*, the view is incredible.",
      "*Here*! Take this, it might help.    *Here*, look at this photo!",
    ],
  },
  {
    headword: "come",
    PoS: "v",
    IPA: "[kʌm]",
    definitions: ["приходить, приезжать", "происходить, случаться"],
    examples: [
      "Can you *come* to the party?    She *came* from Spain last week.",
      "Success *comes* with hard work.",
    ],
  },
  {
    headword: "up",
    PoS: "adv, adj, prep",
    IPA: "[ʌp]",
    definitions: [
      "_adv_ вверх",
      "_adv_ в вертикальном положении",
      "_adj_ законченный, истекший <о времени>",
      "_prep_ <передает движение на более высокий уровень или позицию>",
    ],
    examples: [
      "He looked *up* at the stars.",
      "He stood *up*.",
      "Time is *up*, please stop writing.",
      "The road runs *up* the mountain for ten miles.    We cycled *up* the hill to get a better view.",
    ],
  },
  {
    headword: "one",
    PoS: "num, pron, det",
    IPA: "[wʌn]",
    definitions: [
      "_num_ один",
      "_pron_ некто <вместо 'I', 'you' и т.д.>",
      "_det_ единственный, конкретный",
      "_adj_ один, единый, общий",
    ],
    examples: [
      "I have *one* apple left.",
      "*One* never knows what will happen.    *One* should always be polite.",
      "That is the *one* movie I want to see.",
      "They moved in *one* direction.",
    ],
  },
  {
    headword: "will",
    PoS: "v, n",
    IPA: "[wɪl]",
    definitions: [
      "_v_ <используется для образования будущего времени>",
      "_n_ воля",
    ],
    examples: ["I *will* call you later.", "She has a strong *will*."],
  },
  {
    headword: "see",
    PoS: "v",
    IPA: "[si]",
    definitions: ["видеть", "понимать, осознавать", "встречаться с (кем-либо)"],
    examples: [
      "Can you *see* that bird?",
      "Do you *see* my point now?",
      "I'll *see* you tomorrow.",
    ],
  },
  {
    headword: "any",
    PoS: "det, pron, adv",
    IPA: "[ˈɛni]",
    definitions: [
      "_det, pron_ любой, какой угодно",
      "_det, pron_ хоть какое-то количество <в вопросах или отрицаниях>",
      "_adv_ вообще, хоть сколько-нибудь",
    ],
    examples: [
      "You can take *any* seat.    If *any* of the students have questions, they should ask now.",
      "Do you have *any* money?    I don't have *any* money.    She offered me three suggestions, but I didn't like *any*.",
      "I don't think it matters *any* more.",
    ],
  },
  {
    headword: "from",
    PoS: "prep",
    IPA: "[fɹʌm, fɹəm]",
    definitions: [
      "<указывает на точку отправления или источник>",
      "с позиции, с точки зрения",
      "<указывает на отличие или запрет>",
    ],
    examples: [
      "She's *from* Canada.    I got a letter *from* him.",
      "I can't tell the difference *from* a distance.",
      "The rule prevents us *from* leaving early.",
    ],
  },
  {
    headword: "now",
    PoS: "adv, n",
    IPA: "[naʊ]",
    definitions: ["_adv_ сейчас", "_conj_ поскольку", "_n_ настоящее время"],
    examples: [
      "I'm busy *now*.",
      "*Now* that you're here, we can start.",
      "Let's live in the *now*.",
    ],
  },
  {
    headword: "would",
    PoS: "v",
    IPA: "[wʊd]",
    definitions: [
      "бы",
      "<выражает прошедшее намерение или повторяющееся действие>",
      "<выражает будущее в прошлом>",
    ],
    examples: [
      "I *would* love to join you.    What *would* you do?    If I had the money, I *would* buy that car.    *Would* you like some tea?",
      "If I had the money, I *would* buy that car.",
      "She promised last week that she *would* arrive today.",
    ],
  },
  {
    headword: "make",
    PoS: "v, n",
    IPA: "[meɪk]",
    definitions: [
      "_v_ делать, создавать",
      "_v_ заставлять, побуждать",
      "_n_ вид, марка, конструкция",
    ],
    examples: [
      "She *made* a cake.",
      "This news *makes* me happy.    He *made* me laugh.",
      "What is the *make* of your car?",
    ],
  },
  {
    headword: "look",
    PoS: "v, n",
    IPA: "[lʊk]",
    definitions: ["_v_ смотреть", "_v_ выглядеть", "_n_ взгляд"],
    examples: [
      "*Look* at that painting.",
      "You *look* tired.",
      "He gave me a strange *look*.",
    ],
  },
  {
    headword: "how",
    PoS: "adv, conj",
    IPA: "[haʊ]",
    definitions: ["_adv_ как", "_conj_ как"],
    examples: [
      "*How* did you solve the problem?    *How* long will it take?",
      "*Tell me *how* it works.",
    ],
  },
  {
    headword: "by",
    PoS: "prep, adv",
    IPA: "[baɪ]",
    definitions: ["_prep_ у, рядом с", "с помощью, посредством", "к (сроку)"],
    examples: [
      "The house is *by* the lake.",
      "Written *by* hand.",
      "Finish it *by* Monday.",
    ],
  },
  {
    headword: "who",
    PoS: "pron",
    IPA: "[hu]",
    definitions: ["кто"],
    examples: ["*Who* is calling?    Do you know *who* she is?"],
  },
  {
    headword: "take",
    PoS: "v, n",
    IPA: "[teɪk]",
    definitions: [
      "_v_ брать",
      "_v_ занимать (время)",
      "_v_ отвозить",
      "_n_ дубль <в кино>",
    ],
    examples: [
      "Please *take* one.",
      "This will *take* an hour.",
      "I'll *take* you to school.",
      "The director called for another *take*.",
    ],
  },
  {
    headword: "or",
    PoS: "conj",
    IPA: "[ɔɹ]",
    definitions: ["или"],
    examples: ["Tea *or* coffee?    Is it right *or* wrong?"],
  },
  {
    headword: "tell",
    PoS: "v",
    IPA: "[tɛl]",
    definitions: [
      "сообщать информацию или историю",
      "приказывать или советовать",
      "различать, определять",
    ],
    examples: [
      "I *told* her the truth.    Can you *tell* me a story?",
      "I *told* him to stop.",
      "I can *tell* the twins apart easily.",
    ],
  },
  {
    headword: "OK",
    PoS: "interj, n, v, adj, adv",
    IPA: "[ˌoʊˈkeɪ]",
    definitions: [
      "_interj_ хорошо <выражение согласия или одобрения>",
      "_adj_ хороший, приемлемый",
      "_adv_ удовлетворительно",
      "_n_ согласие",
      "_v_ одобрять",
    ],
    examples: [
      "*OK*, let's begin.",
      "Is your car *OK* to drive?    Everything's *OK* now.",
      "Things are going *OK*.",
      "He gave his *OK* for the plan.",
      "The manager *OK'd* the budget.",
    ],
  },
  {
    headword: "time",
    PoS: "n, v",
    IPA: "[taɪm]",
    definitions: [
      "_n_ время",
      "_n_ раз",
      "_v_ измерять время",
      "_v_ выбирать или устанавливать время для чего-либо",
    ],
    examples: [
      "What *time* is it?",
      "I've seen it three *times*.",
      "The coach *timed* the runners with a stopwatch.",
      "They *timed* the release of the new product to coincide with the holiday season.",
    ],
  },
  {
    headword: "when",
    PoS: "adv, conj, pron",
    IPA: "[wɛn]",
    definitions: [
      "_adv_ когда, в какой момент",
      "_conj_ когда, в то время как",
      "_pron_ какое время",
    ],
    examples: [
      "*When* does the train arrive?",
      "I was studying *when* you called.    I'll call you *when* I'm home.",
      "The sign says the road is closed, but it doesn't specify until *when*.",
    ],
  },
  {
    headword: "hello",
    PoS: "interj, n",
    IPA: "[hɛˈloʊ]",
    definitions: ["_interj_ привет", "_n_ приветствие"],
    examples: [
      "**Hello*, it's good to finally meet you in person.",
      "I said *hello*, but she didn't hear.",
    ],
  },
  {
    headword: "could",
    PoS: "v",
    IPA: "[kʊd]",
    definitions: [
      "мог(ли) бы <выражает вежливую просьбу или предложение>",
      "мог",
      "<выражает вероятность или возможность>",
    ],
    examples: [
      "*Could* you please close the door?",
      "I *could* run faster as a kid.",
      "It *could* rain later today.",
    ],
  },
  {
    headword: "good",
    PoS: "adj, n",
    IPA: "[ɡʊd]",
    definitions: [
      "_adj_ хороший",
      "_n_ добро",
      "_n_ польза",
      "_adj_ X плюс, точно превышая X",
    ],
    examples: [
      "This is a *good* book.",
      "She believes in doing *good*.",
      "The exercise did him a lot of *good*.",
      "I waited a *good* ten minutes.",
    ],
  },
  {
    headword: "why",
    PoS: "adv, conj, interj",
    IPA: "[waɪ]",
    definitions: [
      "_adv_ почему, зачем",
      "_conj_ почему, зачем",
      "_interj_ <выражение удивления, несогласия или паузы>",
    ],
    examples: [
      "*Why* are you late?",
      "Tell me *why* you left.",
      "*Why*, I never thought of that!",
    ],
  },
  {
    headword: "back",
    PoS: "n, adj, adv, v",
    IPA: "[bæk]",
    definitions: [
      "_n_ задняя или обратная сторона чего-либо",
      "_adj_ задний",
      "_adv_ назад",
      "_v_ двигаться или заставлять двигаться назад",
      "_v_ поддерживать",
    ],
    examples: [
      "Write your name on the *back* of the photo.",
      "Use the *back* entrance.",
      "Let's go *back* to the office.",
      "The car started to *back* out of the driveway.",
      "I'll *back* your proposal.",
    ],
  },
  {
    headword: "let",
    PoS: "v",
    IPA: "[lɛt]",
    definitions: ["позволять", "let's: <побуждение к совместному действию>"],
    examples: ["*Let* her explain.", "*Let's* take a break."],
  },
  {
    headword: "mean",
    PoS: "v, adj, n",
    IPA: "[min]",
    definitions: [
      "_v_ значить",
      "_v_ подразумевать, иметь в виду",
      "_adj_ злой, недобрый или скупой",
      "_adj_ <математика, статистика> средний",
      "_n_ среднее арифметическое",
    ],
    examples: [
      "What does this phrase *mean*?    Losing this game will *mean* we're out of the tournament.",
      "I didn't *mean* to interrupt.",
      "That was a *mean* thing to say to her.",
      "The *mean* temperature for the week was 18 degrees Celsius.",
      "To find the *mean*, you add all the numbers and divide by how many numbers there are.",
    ],
  },
  {
    headword: "then",
    PoS: "adv, adj, n",
    IPA: "[ðɛn]",
    definitions: [
      "_adv_ затем, после этого",
      "_adv_ тогда, в то время",
      "_adv_ тогда, в этом случае, следовательно",
      "_adj_ относящийся к тому времени",
    ],
    examples: [
      "We'll have dinner and *then* watch a film.",
      "Back *then*, things were simpler.",
      "If you're busy, *then* I'll go by myself.",
      "The *then* president was giving a speech.",
    ],
  },
  {
    headword: "every",
    PoS: "det",
    IPA: "[ˈɛvɹi]",
    definitions: [
      "_det_ каждый",
      "every other phrase: каждый второй, через один",
    ],
    examples: [
      "*Every* participant received a certificate.    She trains *every* morning.",
      "The class meets *every other* Tuesday.",
    ],
  },
  {
    headword: "thing",
    PoS: "n",
    IPA: "[θɪŋ]",
    definitions: [
      "_n_ вещь, предмет, дело",
      "the thing is: основная проблема/вопрос/дело здесь в следующем",
      "_n_ личное имущество или одежда",
    ],
    examples: [
      "This is my favorite *thing* about the city.",
      "The *thing* is, we're out of time.",
      "She packed her *things* and left.",
    ],
  },
  {
    headword: "more",
    PoS: "det, pron, adv",
    IPA: "[mɔɹ]",
    definitions: ["_det, pron_ больше", "_adv_ больше, более"],
    examples: [
      "We need *more* (data).",
      "This book is *more* interesting than that one.    If you want to pass the exam, you need to study *more*.",
    ],
  },
  {
    headword: "need",
    PoS: "v, n",
    IPA: "[nid]",
    definitions: [
      "нуждаться",
      "необходимость – требование или недостаток чего-либо необходимого",
    ],
    examples: [
      "I *need* a few minutes.    I *need* to go to the bank today.",
      "There's a clear *need* for action.",
    ],
  },
  {
    headword: "give",
    PoS: "v",
    IPA: "[ɡɪv]",
    definitions: ["давать", "уступать давлению или ломаться"],
    examples: [
      "Can you *give* me a ride?    I *gave* her the report.",
      "The old wooden door finally *gave* after the third kick.",
    ],
  },
  {
    headword: "really",
    PoS: "adv",
    IPA: "[ˈɹi(ə)li]",
    definitions: ["действительно", "очень"],
    examples: [
      "Did that *really* happen, or are you joking?",
      "I'm *really* tired after that long trip.",
    ],
  },
  {
    headword: "where",
    PoS: "adv, pron, conj",
    IPA: "[wɛəɹ]",
    definitions: [
      "_adv_ где, куда",
      "_pron_ где, куда",
      "_conj_ в то время как <для сравнения>",
    ],
    examples: [
      "*Where* did you leave the documents?    *Where* are you going tonight?",
      "That's the café *where* we met.    Tell me *where* you plan to go on vacation.",
      "Some people prefer coffee, *where* others prefer tea.",
    ],
  },
  {
    headword: "man",
    PoS: "n",
    IPA: "[mæn]",
    definitions: [
      "_n_ мужчина",
      "_n_ человек <как вид или род>",
      "_interj_ <выражение сильной эмоции: удивления, восхищения, разочарования и т.д.>",
    ],
    examples: [
      "The *man* at the desk will help you.",
      "*Man* has always sought meaning.",
      "*Man*, that was the best concert I've ever been to!",
    ],
  },
  {
    headword: "way",
    PoS: "n, adv",
    IPA: "[weɪ]",
    definitions: [
      "_n_ путь",
      "_n_ способ, метод, манера, средство",
      "_n_ расстояние",
      "_adv_ намного, значительно <используется для усиления>",
    ],
    examples: [
      "We looked for the quickest *way* to the city center.",
      "I like the *way* you handled the situation.",
      "The supermarket is a long *way* from here.",
      "It's *way* too cold to swim today.",
    ],
  },
  {
    headword: "because",
    PoS: "conj, prep",
    IPA: "[biˈkɔz, biˈkʌz]",
    definitions: [
      "_conj_ потому что",
      "because of prep: по причине",
      "_prep_ infml|slang = because of: по причине",
    ],
    examples: [
      "I stayed home *because* I wasn't feeling well.    He left early *because* of the delay.",
      "We had to cancel the picnic *because of* the heavy rain.",
      "I need more coffee, *because* Mondays.    (= I need more coffee because it's Monday and Mondays are difficult)",
    ],
  },
  {
    headword: "work",
    PoS: "v, n",
    IPA: "[wɜɹk]",
    definitions: [
      "_v_ работать – делать усилие",
      "_v_ работать – функционировать или иметь желаемый эффект",
      "_n_ работа – усилие, место, профессия",
    ],
    examples: [
      "I *work* in tech.",
      "This old machine still *works* perfectly.",
      "She has a lot of *work* to do.    She left *work* early today.",
    ],
  },
  {
    headword: "which",
    PoS: "det, pron",
    IPA: "[wɪtʃ]",
    definitions: [
      "_det, pron_ который",
      "_pron_ <используется для ссылки на целое предыдущее предложение или идею>",
    ],
    examples: [
      "*Which* (option) do you prefer?    I forgot *which* (room) it was.",
      "This is the car *which* I want to buy.    The team won the championship, *which* was a huge surprise.",
    ],
  },
  {
    headword: "over",
    PoS: "prep, adj",
    IPA: "[ˈoʊvəɹ]",
    definitions: [
      "_prep_ над",
      "_prep, adv_ по ту сторону, на другую сторону",
      "_adj_ законченный",
      "_adv_ повторно, снова, ещё раз, заново",
      "_adv_ на другую сторону, переворачиваясь, вверх дном",
    ],
    examples: [
      "The lamp hangs *over* the table.",
      "We walked *over* (the bridge).    He climbed *over* (the fence).",
      "The discussion is *over*.    The meeting is *over*.",
      "I asked her to read the instructions *over* one more time.",
      "You should turn the pancake *over* now so it cooks evenly.",
    ],
  },
  {
    headword: "find",
    PoS: "v, n",
    IPA: "[faɪnd]",
    definitions: [
      "_v_ находить, найти",
      "_v_ понять, осознать, обнаружить",
      "_n_ находка",
    ],
    examples: [
      "I couldn't *find* my keys.    She *found* the document in a drawer.",
      "I *find* it difficult to wake up early.",
      "That inexpensive pair of shoes turned out to be a great *find*–they are so comfortable.",
    ],
  },
  {
    headword: "should",
    PoS: "v",
    IPA: "[ʃʊd]",
    definitions: [
      "_v_ должен, следует – выражение долга, обязательства или рекомендации",
      "_v_ должен – выражение вероятности или ожидания",
      "_v_ выражение условного предложения",
    ],
    examples: [
      "You *should* double-check the numbers.    We *should* leave now.",
      "If you leave now, you *should* arrive on time.",
      "If you *should* change your mind, let me know.    *Should* you change your mind, let me know.",
    ],
  },
  {
    headword: "love",
    PoS: "v, n",
    IPA: "[lʌv]",
    definitions: ["_v_ любить", "_n_ любовь – чувство или объект"],
    examples: [
      "I *love* spending time outdoors.    He *loves* his new job because the company culture is very positive.",
      "She felt a deep *love* for her hometown and its history.    She is the *love* of my life.",
    ],
  },
  {
    headword: "talk",
    PoS: "v, n",
    IPA: "[tɔk]",
    definitions: ["говорить", "разговор"],
    examples: [
      "Can we *talk* in private?",
      "His *talk* inspired the whole team.",
    ],
  },
  {
    headword: "two",
    PoS: "num, n",
    IPA: "[tu]",
    definitions: ["_num_ два", "_n_ два объекта; цифра/число 2"],
    examples: [
      "She bought *two* tickets.    They arrived at *two* o'clock.",
      "We'll need a table for *two* at the restaurant.    The clock just struck *two* in the afternoon.",
    ],
  },
  {
    headword: "thank",
    PoS: "v",
    IPA: "[θæŋk]",
    definitions: [
      "_v_ благодарить",
      "thanks interj: <выражает благодарность>",
      "thanks n pl: <выражение благодарности>",
    ],
    examples: [
      "I want to *thank* you for your help.    Don't forget to *thank* the host.",
      '"Here is the coffee you ordered." "*Thanks*!"',
      "Many *thanks* to everyone who volunteered their time today.",
    ],
  },
  {
    headword: "very",
    PoS: "adv, adj",
    IPA: "[ˈvɛɹi]",
    definitions: [
      "_adv_ очень",
      "_adj_ точный, тот самый <используется для усиления существительного>",
    ],
    examples: [
      "That was *very* kind of you.    He's *very* organized.",
      "This is the *very* thing I was looking for.",
    ],
  },
  {
    headword: "only",
    PoS: "adv, adj, conj",
    IPA: "[ˈoʊnli]",
    definitions: [
      "_adv_ только, исключительно",
      "_adj_ один, единственный",
      "_conj_ но <после утверждения, чтобы указать на неожиданное или отрицательное последствие>",
    ],
    examples: [
      "She *only* studies at night.",
      "He was the *only* one who showed up.    She is the *only* person who can help.",
      "I would go, *only* I have too much work.",
    ],
  },
  {
    headword: "too",
    PoS: "adv",
    IPA: "[tu]",
    definitions: ["_adv_ тоже", "_adv_ слишком"],
    examples: ["I'm going *too*.", "This shirt is *too* expensive."],
  },
  {
    headword: "down",
    PoS: "adv, prep, adj",
    IPA: "[daʊn]",
    definitions: [
      "_adv_ вниз",
      "_prep_ вниз по, с <указывает на движение вниз по склону и т.д.>",
      "_prep_ <указывает на место или направление вдоль улицы, дороги или другого линейного объекта>",
      "_adj_ грустный, в унынии",
    ],
    examples: [
      "Please sit *down*.",
      "The ball rolled *down* the hill.",
      "The café is just *down* the street.",
      "She felt *down* after hearing the news.",
    ],
  },
  {
    headword: "little",
    PoS: "adj, adv, n",
    IPA: "[lɪtl]",
    definitions: [
      "_adj_ маленький – по размеру и т.д.",
      "_adj_ мало, немного – по количеству",
      "_adv_ немного, едва",
      "_n_ небольшое количество",
    ],
    examples: [
      "She wrote a *little* note.",
      "We have *little* time left.",
      "He worried *little* about the test.",
      "I only need a *little* of that sauce.",
    ],
  },
  {
    headword: "call",
    PoS: "v, n",
    IPA: "[kɔl]",
    definitions: [
      "_v_ звонить",
      "_v_ называть",
      "_n_ звонок",
      "_v_ кричать или говорить громко",
      "_n_ решение, выбор, суждение",
    ],
    examples: [
      "I'll *call* you this evening.",
      "They *called* it a success.",
      "I missed your *call* earlier.",
      "He *called* out her name from across the street.",
      "The referee made a bad *call* near the end of the game.",
    ],
  },
  {
    headword: "other",
    PoS: "det, pron, adv",
    IPA: "[ˈʌðəɹ]",
    definitions: ["_det_ другой", "_pron_ другие люди или вещи", "_adv_ иначе"],
    examples: [
      "Let's try the *other* approach.    He spoke to the *other* members.",
      "Two students left early, but the *others* stayed.",
      "They couldn't explain the phenomenon *other* than by pure chance.",
    ],
  },
  {
    headword: "never",
    PoS: "adv",
    IPA: "[ˈnɛvəɹ]",
    definitions: ["_adv_ никогда"],
    examples: [
      "I've *never* seen anything like this.    She would *never* agree to that.",
    ],
  },
  {
    headword: "people",
    PoS: "n pl, n, v",
    IPA: "[ˈpipl]",
    definitions: [
      "_n pl_ люди",
      "_n_ народ – группа людей, объединенных общим происхождением или культурой",
      "_v_ населять или заселять место",
    ],
    examples: [
      "*People* need clear communication.    The room was full of *people*.",
      "The study focused on the distinct cultures and languages of the different *peoples* in the region.",
      "The region was *peopled* by nomadic tribes centuries ago.",
    ],
  },
  {
    headword: "feel",
    PoS: "v",
    IPA: "[fil]",
    definitions: [
      "_v_ осязать или трогать",
      "_v_ чувствовать",
      "_n_ ощущение или атмосфера места или ситуации",
    ],
    examples: [
      "Can you *feel* the texture of this fabric?",
      "I *feel* much better today.    I *feel* like we should wait a bit longer.",
      "The house has a wonderful *feel* to it.",
    ],
  },
  {
    headword: "into",
    PoS: "prep",
    IPA: "[ˈɪntu]",
    definitions: [
      "_prep_ <выражает движение к внутренней части чего-либо>",
      "_prep_ <выражает изменение состояния или формы>",
      "_prep_    <выражает заинтересованность в чем-либо>",
    ],
    examples: [
      "She went *into* the hallway.    Let's look *into* this issue.",
      "The discussion quickly turned *into* a serious debate.",
      "She is really *into* jazz music.",
    ],
  },
  {
    headword: "use",
    PoS: "v, n",
    IPA: "[v juz; n jus]",
    definitions: ["_v_ использовать", "_n_ использование"],
    examples: ["Can I *use* your laptop?", "That tool has many *uses*."],
  },
  {
    headword: "day",
    PoS: "n",
    IPA: "[deɪ]",
    definitions: [
      "_n_ день в разных смыслах – период от восхода до заката, период в 24 часа, рабочий период дня и т.д.",
    ],
    examples: [
      "It was a beautiful, sunny *day*.    He took the *day* off.    It was a long *day*.",
    ],
  },
  {
    headword: "year",
    PoS: "n",
    IPA: "[jɪəɹ]",
    definitions: [
      "_n_ год в разных смыслах – например период в 12 месяцев начиная с 1 января",
    ],
    examples: ["She graduated last *year*.    This has been a tough *year*."],
  },
  {
    headword: "try",
    PoS: "v, n",
    IPA: "[tɹaɪ]",
    definitions: [
      "_v_ пытаться сделать что-либо, прилагать усилия",
      "_v_ проверять что-либо, чтобы увидеть, подходит ли оно или работает ли оно",
      "_n_ попытка",
    ],
    examples: [
      "I'll *try* again later.    I will *try* my best to finish the project on time.",
      "You should *try* their method.    You should *try* this new coffee shop.",
      "Give it another *try* before you give up.",
    ],
  },
  {
    headword: "much",
    PoS: "adv, det, pron",
    IPA: "[mʌtʃ]",
    definitions: [
      "_adv_ в большой степени или мере",
      "_det_ много <с неисчисляемыми существительными>",
      "_pron_ большое количество чего-либо",
    ],
    examples: [
      "Thank you very *much* for your help.",
      "We don't have *much* time.",
      "He complained that *much* of the work was left undone.",
    ],
  },
  {
    headword: "even",
    PoS: "adv, adj",
    IPA: "[ˈivən]",
    definitions: [
      "_adv_ даже – акцентирует что-то неожиданное или необычное",
      "_adj_ ровный",
      "_v_ делать ровным или равным",
    ],
    examples: [
      "He didn't *even* reply.",
      "Make sure the edges are *even*.    The surface of the table is perfectly *even*.",
      "We need to *even* out the differences in scores.",
    ],
  },
  {
    headword: "off",
    PoS: "adv, adj, prep",
    IPA: "[ɔf]",
    definitions: [
      "_adv_ прочь, удаляясь, не в рабочем состоянии",
      "_adj_ прочь, удаленный, не в рабочем состоянии",
      "_prep_ удаляясь от",
      "_adj_ испорченный <о еде>",
    ],
    examples: [
      "He drove off without saying goodbye.    Turn your phone *off*.    They broke *off* the arrangement.",
      "The professor's *off* this week, so no lectures.    The light switch is *off*.    The deal is *off*.",
      "She jumped *off* the step.    She took the day *off* work.",
      "This milk smells *off*.",
    ],
  },
  {
    headword: "than",
    PoS: "conj, prep",
    IPA: "[ðæn]",
    definitions: ["_conj_ чем <в сравнениях>", "_prep_ чем <в сравнениях>"],
    examples: [
      "The project cost a lot more *than* we had planned.    This is better *than* expected.",
      "He's taller *than* his brother.",
    ],
  },
  {
    headword: "help",
    PoS: "v, n",
    IPA: "[hɛlp]",
    definitions: ["_v_ помогать", "_n_ помощь"],
    examples: [
      "Could you *help* me with this?",
      "Thanks for your *help* earlier.",
    ],
  },
  {
    headword: "California",
    PoS: "n",
    IPA: "[ˌkælɪˈfɔɹnjə, -niə]",
    definitions: ["Калифорния"],
    examples: [
      "She's moving to *California* next month.    *California* is known for its innovation.",
    ],
  },
  {
    headword: "first",
    PoS: "det, adv, n",
    IPA: "[fɜɹst]",
    definitions: [
      "_det_ первый",
      "_adv_ перед всем остальным / всеми остальными",
      "_n_ начало чего-либо",
    ],
    examples: [
      "He finished *first* in the race.",
      "Let's clarify the goal *first*.",
      "At *first*, I thought it was a joke.    That performance was a career *first*.",
    ],
  },
  {
    headword: "guy",
    PoS: "n",
    IPA: "[ɡaɪ]",
    definitions: [
      "_n_ мужчина, парень <неформально>",
      "_n_ человек <в обращении к группе, неформально>",
    ],
    examples: [
      "He's a reliable *guy*.    That *guy* knows what he's doing.",
      "Hey, *guys*, let's go get some lunch.",
    ],
  },
  {
    headword: "sure",
    PoS: "adj, interj, adv",
    IPA: "[ʃʊəɹ]",
    definitions: [
      "_adj_ уверенный, не сомневающийся",
      "_interj_ конечно, безусловно",
      "_adv_ конечно, безусловно",
    ],
    examples: [
      "Are you *sure* this will work?",
      "*Sure*, I'll take care of it.",
      "He *sure* does talk a lot.",
    ],
  },
  {
    headword: "happen",
    PoS: "v",
    IPA: "[ˈhæpən]",
    definitions: [
      "_v_ происходить, случаться",
      "_v_ случаться по чистой случайности, без плана",
    ],
    examples: [
      "What exactly *happened* yesterday?    Mistakes *happen* sometimes.",
      "I just *happened* to be in the area when she called.",
    ],
  },
  {
    headword: "sorry",
    PoS: "adj, interj",
    IPA: "[ˈsɔɹi]",
    definitions: [
      "_adj_ сожалеющий, извиняющийся",
      "_interj_ <выражает извинение, сожаление или сочувствие>",
      "_adj_ сочувствующий несчастью другого",
      "_adj_ жалкий, ничтожный (о чем-либо)",
    ],
    examples: [
      "I'm *sorry* for the delay.",
      "*Sorry*, I didn't hear you.",
      "I'm *sorry* for anyone who missed the breathtaking sunset.",
      "That was a pretty *sorry* excuse.",
    ],
  },
  {
    headword: "life",
    PoS: "n",
    IPA: "[laɪf]",
    definitions: [
      "жизнь в разных смыслах – состояние, деятельность, энергия и т.д.",
    ],
    examples: ["He chose a new *life* abroad.    *Life* is full of surprises."],
  },
  {
    headword: "after",
    PoS: "prep, adv, conj",
    IPA: "[ˈæftəɹ]",
    definitions: [
      "_prep_ после",
      "_adv_ потом, позднее",
      "_conj_ после того, как",
    ],
    examples: [
      "Let's meet *after* the meeting.",
      "He arrived shortly *after*.",
      "*After* she left, things changed.    After* the rain stopped, we went outside.",
    ],
  },
  {
    headword: "please",
    PoS: "adv, v",
    IPA: "[pliz]",
    definitions: [
      "_adv_ пожалуйста",
      "_v_ угождать; доставлять удовольствие или удовлетворение",
      "_conj_ <выражает вежливую просьбу>",
      "_conj_ <выражает раздражение, сомнение или несогласие>",
    ],
    examples: [
      "*Please* follow the instructions.",
      "He tries too hard to *please* others.",
      "*Please*, tell me the truth.",
      "He's going to finish that in one day? *Please*.",
    ],
  },
  {
    headword: "still",
    PoS: "adv, conj, adj, n",
    IPA: "[stɪl]",
    definitions: [
      "_adv_ всё ещё",
      "_adv_ еще больше",
      "_adv_ тем не менее, однако",
      "_adj, adv_  без движения, спокойный/спокойно",
      "_n_ аппарат, используемый для дистилляции жидкостей",
    ],
    examples: [
      "I'm *still* thinking about it.    It's *still* raining outside.",
      "I liked the first act, the second act was better, and the finale was better *still*.",
      "He was tired, but *still* finished the race.",
      "The room was completely *still*.    She sat *still*, lost in thought.",
      "The distillery's tour included a demonstration of the antique *still*.",
    ],
  },
  {
    headword: "wait",
    PoS: "v",
    IPA: "[weɪt]",
    definitions: ["_v_ ждать", "_n_ ожидание"],
    examples: ["*Wait* here a moment.", "The *wait* took over an hour."],
  },
  {
    headword: "new",
    PoS: "adj, adv",
    IPA: "[nu]",
    definitions: [
      "_adj_ новый",
      "_adv_ недавно, ново <только в составе сложных слов>",
    ],
    examples: [
      "She got a *new* job.    This policy is *new* to me.",
      "The farmer loved the smell of *new*-mown hay.",
    ],
  },
  {
    headword: "before",
    PoS: "prep, adv, conj",
    IPA: "[biˈfɔɹ]",
    definitions: [
      "_prep_ до",
      "_adv_ раньше, в прошлом",
      "_conj_ до того, как",
    ],
    examples: [
      "I need to finish this report *before* noon.",
      "I've seen that movie *before*.",
      "Wash your hands *before* you eat.",
    ],
  },
  {
    headword: "keep",
    PoS: "v",
    IPA: "[kip]",
    definitions: [
      "_v_ поддерживать в определенном состоянии",
      "_v_ оставаться в определенном состоянии",
      "_v_ сохранять или хранить что-либо в своем распоряжении",
      "_v_ продолжать делать что-либо",
    ],
    examples: [
      "*Keep* your files organized.",
      "*Keep* quiet during the movie.",
      "She *kept* the receipt.",
      "We need to *keep* walking to reach the summit before sunset.",
    ],
  },
  {
    headword: "long",
    PoS: "adj, adv, v",
    IPA: "[lɔŋ]",
    definitions: [
      "_adj_ длинный",
      "_adj_ продолжительный, большой во времени",
      "_adv_ долго, в течение длительного времени",
      "_v_ тосковать, страстно желать",
    ],
    examples: [
      "This is a *long* book.",
      "It was a *long* wait for the train.",
      "I've waited *long* enough.    Have you worked here *long*?",
      "He felt a deep *longing* for home.",
    ],
  },
  {
    headword: "great",
    PoS: "adj, interj",
    IPA: "[ɡɹeɪt]",
    definitions: [
      "_adj_ очень большой",
      "_adj_ отличный, превосходный, замечательный",
      "_interj_ <выражение радости и удовлетворения насчет чего-либо>",
    ],
    examples: [
      "He achieved a *great* success in his career.    The discovery was of *great* importance to science.",
      "That's a *great* idea.    That was a *great* movie!",
      '"We got the funding for the project!" "*Great*! That\'s fantastic news."',
    ],
  },
  {
    headword: "hear",
    PoS: "v",
    IPA: "[hɪəɹ]",
    definitions: [
      "_v_ слышать – воспринимать звук ухом",
      "_v_ узнать, получить информацию",
      "_v_ слушать официально (дело, свидетеля)",
    ],
    examples: [
      "Can you *hear* the music?",
      "Did you *hear* about the new policy?",
      "The judge will *hear* the case next week.",
    ],
  },
  {
    headword: "ask",
    PoS: "v",
    IPA: "[æsk]",
    definitions: ["_v_ спрашивать", "_v_ просить", "_n_ запрос, просьба"],
    examples: [
      "Let me *ask* you something.",
      "He *asked* for a glass of water.",
      "His salary *ask* was too high.",
    ],
  },
  {
    headword: "put",
    PoS: "v",
    IPA: "[pʊt]",
    definitions: [
      "_v_ помещать в определенное место или положение",
      "_v_ выражать, формулировать (словами)",
    ],
    examples: [
      "*Put* your phone on the table.    She *put* the cup on the shelf.",
      "I'm not sure how to *put* this, but I need a break.",
    ],
  },
  {
    headword: "maybe",
    PoS: "adv",
    IPA: "[ˈmeɪbi]",
    definitions: ["_adv_ возможно, может быть"],
    examples: ["*Maybe* we can try again."],
  },
  {
    headword: "again",
    PoS: "adv",
    IPA: "[əˈɡɛn]",
    definitions: ["_adv_ снова, еще раз, повторно"],
    examples: ["Let's watch that movie *again*."],
  },
  {
    headword: "god",
    PoS: "n",
    IPA: "[ɡɑd]",
    definitions: [
      "_n_ в монотеизме: высшее существо, создатель и правитель Вселенной",
      "_n_ в политеизме: одно из нескольких сверхъестественных существ, почитающихся как имеющих власть над природой и/или судьбами людей",
      "_n_ <перен.> очень почитаемый или влиятельный человек",
    ],
    examples: [
      "She prayed to *God* for strength.",
      "The ancient Greeks worshipped many *gods*.",
      "He is considered a soccer *god* in his home country.",
    ],
  },
  {
    headword: "nothing",
    PoS: "pron",
    IPA: "[ˈnʌθɪŋ]",
    definitions: [
      "_pron_ <указывает на отсутствие вещи или набора вещей>",
      "_n_ <указывает на понятие нулевой/тривиальной ценности/важности>",
    ],
    examples: [
      "There was *nothing* left in the fridge.",
      "The repair cost *nothing* compared to replacing the whole machine.",
    ],
  },
  {
    headword: "last",
    PoS: "adj, v",
    IPA: "[læst]",
    definitions: [
      "_adj_ последний – самый недавний",
      "_adj_ последний – конечный, окончательный",
      "_adv_ наиболее недавно",
      "_v_ длиться, продолжаться",
    ],
    examples: [
      "We went to the cinema *last* Friday.",
      "That was the *last* item on the list.    This is the *last* chapter of the book.",
      "I *last* spoke to him two days ago.    Did you *last* visit that city in 2020?",
      "The meeting *lasted* three hours.",
    ],
  },
  {
    headword: "home",
    PoS: "n, adv, adj",
    IPA: "[hoʊm]",
    definitions: [
      "_n_ место, где кто-то живет – здание, город, страна",
      "_adv_ домой – к месту, где кто-то живет",
      "_adj_ относящийся к дому, домашний",
      "home in on v: {сосредоточить внимание и/или действие на данной цели} с возрастающей точностью",
    ],
    examples: [
      "There's no place like *home*.",
      "We returned to *home* after dinner.    Let's go *home* now.",
      "Their new business focuses on selling *home* decor and furnishings.",
      "The committee tried to *home in on* the main factors causing the recent drop in sales.",
    ],
  },
  {
    headword: "away",
    PoS: "adv",
    IPA: "[əˈweɪ]",
    definitions: [
      "_adv_ в другое место, прочь, в другом месте, вдали",
      "_adv_ без перерыва",
      "_adj_ <спорт> играющий на чужом поле",
    ],
    examples: [
      "He looked *away* during the conversation.    They live far *away* from the city.",
      "He worked *away* at his project all night.",
      "We have an *away* game against the rival team.",
    ],
  },
  {
    headword: "night",
    PoS: "n",
    IPA: "[naɪt]",
    definitions: ["_n_ ночь – период темноты между заходом и восходом солнца"],
    examples: [
      "It was a quiet *night*.    We drove through the *night* to get there.",
    ],
  },
  {
    headword: "stop",
    PoS: "v, n",
    IPA: "[stɑp]",
    definitions: [
      "_v_ останавливать(ся) – прекращать движение или действие",
      "_n_ остановка – место или действие",
    ],
    examples: [
      "The car *stopped* at the traffic light.    Please *stop* making noise.",
      "The bus *stop* is just around the corner.    We made a short *stop* before continuing.",
    ],
  },
  {
    headword: "through",
    PoS: "prep, adj, adv",
    IPA: "[θɹu]",
    definitions: [
      "_prep_ через – из одного конца или стороны в другой",
      "_prep_ сквозь, насквозь",
      "_prep_ от начала до конца (чего-либо), завершив (что-либо)",
      "_adv_ от начала до конца, завершив",
      "_adj_ законченный, завершенный",
    ],
    examples: [
      "We drove *through* the tunnel.",
      "The light came *through* the curtain.",
      "I finally got *through* reading that long novel.",
      "The proposal went *through* after hours of debate.",
      "The meeting went very smoothly; we were *through* by noon.",
    ],
  },
  {
    headword: "may",
    PoS: "v, n",
    IPA: "[meɪ]",
    definitions: [
      "_v_ выражает разрешение (можно)",
      "_v_ выражает возможность или вероятность (может быть)",
      "_v_ выражает пожелание или надежду (пусть)",
      "May n: май – пятый месяц года",
    ],
    examples: [
      "*May* I have a glass of water?    You *may* leave early today.",
      "It *may* rain later this afternoon.",
      "*May* you have a long and happy life.",
      "Her birthday falls in the middle of *May*.",
    ],
  },
  {
    headword: "three",
    PoS: "num, n",
    IPA: "[θɹi]",
    definitions: ["_num_ три", "_n_ три объекта; цифра/число 3"],
    examples: [
      "She has *three* notebooks.",
      "She wrote the number *three* on the whiteboard.    The contract must be signed by the principal, the guarantor, and the lawyer–the key *three*.",
    ],
  },
  {
    headword: "leave",
    PoS: "v",
    IPA: "[liv]",
    definitions: [
      "_v_ уходить (из)",
      "_v_ уходить от, покидать (кого-то)",
      "_v_ оставлять",
      "_n_ разрешение отсутствовать (например на работе), период отсутствия или официальное разрешение что-либо сделать",
    ],
    examples: [
      "I have to *leave* (the office) by six.",
      "She had to *leave* her family and move overseas for her new job.",
      "She *left* a note on the table.",
      "She has been granted a three-month *leave* to travel abroad.    She is currently on *leave* and won't be back in the office until next week.",
    ],
  },
  {
    headword: "friend",
    PoS: "n",
    IPA: "[fɹɛnd]",
    definitions: [
      "_n_ друг – {человек, которого знаешь и любишь}, союзник/сторонник, покровитель/благодетель, и т.д.",
    ],
    examples: [
      "He's a *friend* from college.    She is a true *friend* of the arts.",
    ],
  },
  {
    headword: "believe",
    PoS: "v",
    IPA: "[bɪˈliv]",
    definitions: [
      "_v_ верить (во что-то / чему-то) – принимать что-то за правду, считать истинным",
      "_v_ верить (кому-то) – принимать, что данный человек говорит правду",
    ],
    examples: [
      "I *believe* in her honesty.",
      "He wanted to *believe* his friend, but the facts didn't add up.",
    ],
  },
  {
    headword: "live",
    PoS: "v, adj, adv",
    IPA: "[v lɪv; laɪv]",
    definitions: [
      "_v_ жить – быть живым",
      "_v_ жить – проживать в определенном месте",
      "_adj_ имеющий жизнь, энергию или текущую актуальность",
      "_adv_ имея жизнь, энергию или текущую актуальность",
      "_adj, adv_ в прямом эфире, не записанный",
    ],
    examples: [
      "Despite the harsh conditions, the plant managed to *live* and flourish.    She felt she truly began to *live* only after she quit her stressful job.",
      "They *live* in Los Angeles.",
      "The technician warned us about the *live* wire. <with current>    The satellite link went *live* at midnight.    The band's *live* concert was a huge success. <in person>",
      "Handle this circuit carefully, it's operating *live*.    The network is still running *live* while the updates are applied.    The comedian performed *live* at the theater.",
      "This is a *live* broadcast.    The concert will be broadcast *live* tonight.",
    ],
  },
  {
    headword: "must",
    PoS: "v",
    IPA: "[mʌst]",
    definitions: [
      "_v_ должен, обязан – выражает необходимость или обязательство",
      "_v_ должно быть, вероятно – выражает высокую вероятность",
      "_n_ нечто обязательное, необходимое",
    ],
    examples: [
      "You *must* finish your work today.",
      "She *must* be very tired after that long flight.",
      "Learning the basics is a *must* for any beginner.",
    ],
  },
  {
    headword: "care",
    PoS: "v, n",
    IPA: "[kɛəɹ]",
    definitions: [
      "_v_ заботиться, испытывать беспокойство или интерес",
      "_n_ забота, внимание, осторожность",
      "_v_ хотеть, желать <обычно в вопросах или отрицаниях>",
    ],
    examples: [
      "I really *care* about the outcome.",
      "She took *care* of the arrangements.",
      "Would you *care* for another cup of coffee?",
    ],
  },
  {
    headword: "place",
    PoS: "n, v",
    IPA: "[pleɪs]",
    definitions: [
      "_n_ место",
      "_v_ класть, помещать",
      "_v_ делать – например звонок, заказ, объявление, заявку, ставку",
      "_n_ положение в соревновании, спорте",
    ],
    examples: [
      "This is a nice *place* to study.    This is a beautiful *place* to live.",
      "She *placed* the folder on the desk.",
      "You need to *place* the order online.    The construction company plans to place a *bid* for the city's new bridge project.",
      "He finished in third *place* in the marathon.",
    ],
  },
  {
    headword: "better",
    PoS: "adj, adv, n",
    IPA: "[ˈbɛtəɹ]",
    definitions: [
      '_adj_ лучше – сравнительная степень от "good"',
      '_adv_ лучше – сравнительная степень от "well"',
      "_v_ улучшать, превосходить",
      "_n_ более предпочтительный или лучший вариант",
    ],
    examples: [
      "This solution is *better* than the last one.",
      "She sings *better* now after practice.",
      "He wants to *better* his personal record.",
      "His move abroad was definitely for the *better*.",
    ],
  },
  {
    headword: "late",
    PoS: "adj, adv",
    IPA: "[leɪt]",
    definitions: [
      "_adj, adv_ поздний, поздно – после нужного времени <негативно>",
      "_adj, adv_ поздний, поздно – после обычного времени <нейтрально>",
      "_adj_ recently deceased.",
    ],
    examples: [
      "He was *late* to the meeting.    The train arrived *late* due to snow.",
      "The *late*-blooming roses in the garden provided color well into November.    The sun rises much *later* in the winter than it does in the summer.",
      "We celebrated the life and work of the *late* Professor Miller at the dedication ceremony.",
    ],
  },
  {
    headword: "start",
    PoS: "v, n",
    IPA: "[stɑɹt]",
    definitions: [
      "_v_ начинать, приступать к чему-либо",
      "_v_ запускать, приводить в действие (машину)",
      "_n_ начало, отправная точка",
      "_n_ внезапное, резкое движение из-за удивления или испуга",
    ],
    examples: [
      "Let's *start* with introductions.",
      "I couldn't *start* the car this morning.",
      "The *start* was delayed.    He was there from the very *start*.",
      "The loud noise gave him a *start*.",
    ],
  },
  {
    headword: "kill",
    PoS: "v, n",
    IPA: "[kɪl]",
    definitions: [
      "_v_ убивать – лишать жизни, умертвлять",
      "_v_ уничтожать, прекращать действие",
      "_n_ убийство (на охоте или в спорте)",
      "_v_ <например в комедии> выступить исключительно хорошо или добиться огромного успеха у зрителей",
    ],
    examples: [
      "The virus can *kill* if untreated.",
      "We need to *kill* this project before it wastes more resources.",
      "Hunters are required to tag every *kill* immediately upon retrieval to prevent poaching.",
      "You could tell the joke was *killing* just by listening from backstage.",
    ],
  },
  {
    headword: "woman",
    PoS: "n",
    IPA: "[ˈwʊmən]",
    definitions: ["_n_ женщина"],
    examples: ["She's a strong and independent *woman*."],
  },
  {
    headword: "mom",
    PoS: "n",
    IPA: "[mɑm]",
    definitions: ["_n_ мать, мама <неформально>"],
    examples: ["My *mom* is visiting next week."],
  },
  {
    headword: "show",
    PoS: "v, n",
    IPA: "[ʃoʊ]",
    definitions: [
      "_v_ показывать – давать возможность увидеть что-то",
      "_v_ показывать – демонстрировать или объяснять",
      "_v_ проявлять (некоторую характеристику)",
      "_n_ шоу",
    ],
    examples: [
      "Please *show* me the results.",
      "She showed the class how to solve the problem.",
      "Her dedication to fitness *shows* in her energy levels and physical health.",
      "That was a great *show*.",
    ],
  },
  {
    headword: "meet",
    PoS: "v",
    IPA: "[mit]",
    definitions: [
      "_v_ встречать – приходить в то же место, что и кто-то/что-то, по договоренности или случайно",
      "_v_ впервые познакомиться с кем-то",
      "_v_ соответствовать или удовлетворять требованию или стандарту",
      "_n_ спортивное соревнование, особенно по легкой атлетике или плаванию",
    ],
    examples: [
      "I'll *meet* you at the entrance.    I didn't expect to *meet* her at the bookstore yesterday.",
      "I haven't *met* your new colleague yet.",
      "The quality of the work didn't *meet* the required standard.",
      "She broke a record at the last swimming *meet*.",
    ],
  },
  {
    headword: "always",
    PoS: "adv",
    IPA: "[ˈɔlweɪz]",
    definitions: [
      "_adv_ всегда",
      "_adv_ если это необходимо или если нет лучшего варианта",
    ],
    examples: [
      "She *always* brings a notebook.",
      "You can *always* call me if you need help.    If the main road is closed, you can *always* take the scenic route.",
    ],
  },
  {
    headword: "around",
    PoS: "prep, adj, adv",
    IPA: "[əˈɹaʊnd]",
    definitions: [
      "_prep_ вокруг (чего-либо) – с центром на (чем-либо) в разных смыслах",
      "_adj_ <неформально> присутствующий; доступный; поблизости",
      "_prep_ в различных местах внутри или на всей территории (чего-либо)",
      "_adv_ вблизи, поблизости",
      "_adv_ приблизительно, примерно",
    ],
    examples: [
      "The planets revolve *around* the sun.",
      "Is your manager *around*? I need to ask a question.    I'll be *around* until five o'clock.",
      "We walked *around* the park.",
      "Is there a store *around* here?",
      "I think she is *around* forty years old.",
    ],
  },
  {
    headword: "old",
    PoS: "adj",
    IPA: "[oʊld]",
    definitions: [
      "_adj_ старый",
      "_adj_ имеющий указанный возраст",
      "_adj_ больше не интересный после длительного повторения",
    ],
    examples: [
      "This is an *old* photo.",
      "How *old* is that building?    The contract is two days *old* and already has issues.",
      "That joke is getting *old*.",
    ],
  },
  {
    headword: "ever",
    PoS: "adv",
    IPA: "[ˈɛvəɹ]",
    definitions: [
      "_adv_ постоянно, непрерывно",
      "_adv_ когда-либо",
      "_adv_ <неформально> в самом деле, чрезвычайно – усилитель",
    ],
    examples: [
      "The company has to adapt to the *ever*-evolving market.",
      "Have you *ever* been to Rome?",
      "Was I *ever* excited when they announced the winner!",
    ],
  },
  {
    headword: "big",
    PoS: "adj, adv",
    IPA: "[bɪɡ]",
    definitions: [
      "_adj_ большой",
      "_adj_ <неформально> щедрый, великодушный",
      "_adj_ популярный",
      "_adv_ в значительной мере; в большом масштабе",
    ],
    examples: [
      "That's a *big* decision.",
      "That was incredibly *big* of him to cover my shift with such short notice.",
      "Minimalist design is still very *big* in home decor.",
      "The company bet *big* on the new technology, and it paid off.    If you want success, you have to think *big*.",
    ],
  },
  {
    headword: "move",
    PoS: "v, n",
    IPA: "[muv]",
    definitions: [
      "_v_ двигать(ся); перемещать(ся)",
      "_v_ переезжать",
      "_n_ переезд",
      "_v_ вызвать сильную эмоцию или сочувствие",
      "_n_ действие, предпринятое для достижения цели",
    ],
    examples: [
      "We need to *move* this table to the corner.",
      "He *moved* to a new apartment.",
      "The *move* took two days.",
      "The simple beauty of the mountains always *moves* me.",
      "Making that investment was a smart *move*.",
    ],
  },
  {
    headword: "run",
    PoS: "v, n",
    IPA: "[ɹʌn]",
    definitions: [
      "_v_ бежать",
      "_v_ работать, действовать (о машине, программе)",
      "_v_ управлять или руководить (бизнесом, организацией)",
      "_v_ быть кандидатом на выборах",
      "_n_ непрерывный период успешной или заметной работы/деятельности",
    ],
    examples: [
      "He can *run* a mile in under six minutes.",
      "The car is *running* smoothly after the repair.",
      "She *runs* her own successful company.    They *run* a small business.",
      "She plans to *run* for mayor in the next election.",
      "Their experimental software had a successful test *run* for six weeks.",
    ],
  },
  {
    headword: "house",
    PoS: "n, v",
    IPA: "[n haʊs; v haʊz]",
    definitions: [
      "_n_ дом – здание для проживания",
      "_v_ предоставить место для проживания или хранения",
      "_n_ компания; фирма; учреждение (часто в индустрии моды, финансов)",
      "_n_ аудитория; зрительный зал (театра, кинотеатра)",
      "законодательный орган, палата (часть парламента)",
    ],
    examples: [
      "Their *house* is on the corner.",
      "The museum *houses* a rare collection of ancient artifacts.",
      "She works for a famous fashion *house* in Milan.",
      "The theater played to a full *house* on opening night.",
      "The bill was narrowly passed by the lower *house* of parliament.",
    ],
  },
  {
    headword: "play",
    PoS: "v, n",
    IPA: "[pleɪ]",
    definitions: [
      "_v_ играть – заниматься деятельностью ради отдыха или развлечения",
      "_v_ участвовать в спортивной игре",
      "_v_ действовать или вести себя указанным образом",
      "_v_ (вос)производить звук (особенно музыку), видео или театральные представления",
      "_n_ пьеса для театра",
    ],
    examples: [
      "After finishing their homework, the students went out to *play*.",
      "He *plays* basketball every weekend.    Our team is *playing* the champions next Saturday.",
      "The coach told the team they had to *play* fair to win the respect of their opponents.",
      "The band started to *play* their opening song to a cheering crowd.    The new documentary is *playing* in theaters next week.",
      "The *play* was fantastic.",
    ],
  },
  {
    headword: "name",
    PoS: "n, v",
    IPA: "[neɪm]",
    definitions: [
      "_n_ имя – идентификация",
      "_n_ имя – репутация",
      "_n_ имя – власть, основание",
      "_v_ называть – дать кому-то или чему-то имя",
      "_v_ называть – упомянуть кого-то или что-то по имени",
    ],
    examples: [
      "What's your *name*?    What is the *name* of that flower?",
      "She worked hard for years to make a *name* for herself in the field of architecture.",
      "All purchases are made in the company's *name* to maintain clear records.    The representative gave a speech in the *name* of all the attendees.",
      "They *named* their daughter Lily.",
      "Can you *name* three capital cities in Europe?",
    ],
  },
  {
    headword: "kind",
    PoS: "n, adj",
    IPA: "[kaɪnd]",
    definitions: [
      "_n_ вид",
      "kind of adv: <разговорное> немного, в некоторой мере, как бы",
      "in kind adv a: товарами или услугами (в отличие от денег)",
      "in kind adv b: взаимно, подобно, эквивалентно",
      "_adj_ добрый",
    ],
    examples: [
      "What *kind* of music is this?",
      "She was *kind of* upset when she heard the news.",
      "Instead of paying cash, the farmer offered to pay in *kind* with fresh produce.",
      "His insult was immediately met with retaliation in *kind*.",
      "She's a very *kind* person.",
    ],
  },
  {
    headword: "lot",
    PoS: "n",
    IPA: "[lɑt]",
    definitions: [
      "_n_ много",
      "a lot adv: в значительной мере или часто",
      "_n_ <неформально> некоторое количество людей, взятых вместе",
      "_n_ инструмент случайного выбора, наприер игральная кость или кусок бумаги",
      "_n_ участок земли",
    ],
    examples: [
      "We have *a lot* to do today.    She told me *lots* of interesting stories about her trip abroad.",
      "He worries a *lot* about his job.",
      "She was impressed by the bright *lot* of young interns starting this year.",
      "We will draw *lots* for the order of presentations tomorrow morning.",
      "They plan to build a house on that empty *lot*.",
    ],
  },
  {
    headword: "most",
    PoS: "det, n, adv, suffix, pron",
    IPA: "[moʊst]",
    definitions: [
      "_det, pron_ большинство",
      "_adv_ наиболее",
      "_n_ наибольшее количество",
      "_adv_ очень; весьма",
    ],
    examples: [
      "*Most* (of the) people agree with the decision.    *The committee held a vote, and *most* were in favor of the change.    We reviewed all the applications, and *most* met the minimum requirements.",
      "That was the *most* interesting part.",
      "*You should make the *most* of your time abroad by traveling widely.    We have reached the *most* that the current budget will allow for marketing.",
      "The meal was *most* delicious.",
    ],
  },
  {
    headword: "girl",
    PoS: "n",
    IPA: "[ɡɜɹl]",
    definitions: ["девочка; девушка"],
    examples: ["The *girl* gave a speech."],
  },
  {
    headword: "Mister",
    PoS: "n",
    IPA: "[ˈmɪstəɹ]",
    definitions: [
      "_n_ <в письменной форме обычно сокращается до *Mr.*> мистер – общее уважительное звание",
      "_n_ мистер – используется само по себе как фамильярное обращение",
    ],
    examples: [
      "*Mister* Clark is our teacher.    Please ensure *Mr.* Michael Lee receives a copy of the finalized agenda.    *Mr.* Secretary, we await your report on the budget amendment.",
      "Move that car now, *Mister*, or it's getting towed.",
    ],
  },
  {
    headword: "understand",
    PoS: "v",
    IPA: "[ˌʌndɚˈstænd]",
    definitions: [
      "_v_ понимать",
      "_v_ делать вывод несмотря на потенциально неполное знание",
      "_v_ заполнять пробел из контекста",
    ],
    examples: [
      "I *understand* what you're saying.    I don't *understand* the instructions.",
      "I *understand* the meeting has been postponed until tomorrow.    Am I to *understand* that you refuse to accept the terms of the agreement?",
      'When she said she was "going home," the destination "her own house" was *understood*.    In the phrase "Ready when you are," the verb "I will be" is *understood* before "ready."',
    ],
  },
  {
    headword: "own",
    PoS: "adj, v",
    IPA: "[oʊn]",
    definitions: [
      "_adj_ собственный, личный, принадлежащий кому-то",
      "_v_ владеть",
      "_v_ признавать, сознавать, допускать",
      "_v_ полностью владеть или принимать (например свое качество или ситуацию)",
    ],
    examples: [
      "Do you *own* this car?",
      "She has her *own* studio.",
      "She wouldn't *own* her mistake, even when presented with the evidence.    The company was slow to *own* the negative impact of the new product launch.",
      "After years of hesitation, she finally learned to *own* her natural leadership skills.    The athlete *owns* his success; he doesn't apologize for his talent.    She used to be shy about her accent, but now she totally *owns* it.",
    ],
  },
  {
    headword: "dad",
    PoS: "n",
    IPA: "[dæd]",
    definitions: [
      "_n_ отец, родитель мужского пола – особенно в обращении или при неформальном упоминании",
    ],
    examples: ["My *dad* works in finance."],
  },
  {
    headword: "might",
    PoS: "v, n",
    IPA: "[maɪt]",
    definitions: [
      "_v_ возможно – выражает небольшой возможности или вероятности",
      "_v_ мог бы – выражает вежливое предложение или совет",
      "_v_ <используется, чтобы вежливо спросить разрешение>",
      "_v_ мог – прошедшее время от *may* в косвенной речи",
      "_n_ мощь; сила; могущество",
    ],
    examples: [
      "We *might* be late.    It *might* rain later, so take an umbrella.",
      "You *might* want to check the schedule again before you leave.",
      "*Might* I suggest a different approach?",
      "He said he *might* join us after dinner.",
      "The judge ruled with the full *might* of the law behind him.",
    ],
  },
  {
    headword: "course",
    PoS: "n",
    IPA: "[kɔɹs]",
    definitions: [
      "*of course* adv, interj: конечно, разумеется, безусловно, натурально",
      "_n_ курс – ряд уроков или лекций по определенному предмету",
      "_n_ курс – направление, по которому что-то движется",
      "_n_ один из этапов приема пищи",
      "*run its course*: прийти к естественному концу",
    ],
    examples: [
      'She offered to help, and *of course* we accepted immediately.    "Did you enjoy the concert?" – "*Of course*! It was fantastic."',
      "I signed up for a programming *course*.",
      "The river changed its *course*.",
      "The main *course* was delicious.",
      "The company decided to let the current advertising campaign *run its course* before launching a new one.",
    ],
  },
  {
    headword: "such",
    PoS: "det, pron",
    IPA: "[sʌtʃ]",
    definitions: [
      "_det_ такой – используется для сравнения с чем-то, подразумеваемым контекстом",
      "_det_ такой, столь – усилитель",
      "_pron_ что-то/кто-то подобные упомянутым выше",
      "as such: как таковой – в разных смыслах",
      "such as prep: такой как",
    ],
    examples: [
      "The community leaders oppose *such* development plans.",
      "It was *such* a surprise.    I've never seen *such* a beautiful view.    We had *such* a wonderful time at your party last night.",
      'He provided excellent advice; we rarely receive *such* from a consultant. <"such" заменяет "such excellent advice">',
      "You are the team leader, and you should behave *as such* in all meetings.    This is not an official rule *as such*, but it's strongly encouraged by management.    The document contains classified information; *as such*, it cannot leave the premises.",
      "The library offers services *such as* free internet access and printing.    I cannot approve any expenses *such as* these without a receipt.",
    ],
  },
  {
    headword: "also",
    PoS: "adv",
    IPA: "[ˈɔlsoʊ]",
    definitions: ["_adv_ тоже, также", "_conj_ к тому же, сверх того"],
    examples: [
      "I'm *also* interested in history.",
      "She is a talented singer; *also*, she plays the piano.",
    ],
  },
  {
    headword: "fine",
    PoS: "adj, adv, n, v",
    IPA: "[faɪn]",
    definitions: [
      "_adj, adv, interj_ хорошо, приемлемо",
      "_adj_ отличный, превосходный",
      "_adj_ очень тонкий или измельченный",
      "_n_ штраф – деньги, которые нужно заплатить в качестве наказания",
      "_v_ (о)штрафовать",
    ],
    examples: [
      '"Is the coffee too hot?" – "No, it\'s *fine*, thank you."    The new system is running *fine* after the installation of the update.    "You need to finish this report before you leave." – "*Fine*, I\'ll do it."',
      "The concert hall has the *finest* acoustics in the entire city.",
      "The lens was protected by a *fine* layer of transparent coating.    We swept the porch clear of the *fine* snow.",
      "He had to pay a *fine* for parking illegally.",
      "He was *fined* for speeding.",
    ],
  },
  {
    headword: "listen",
    PoS: "v, n",
    IPA: "[ˈlɪsən]",
    definitions: [
      "_v_ слушать",
      "_v_ обращать внимание на совет, предупреждение или объяснение",
      "_n_ акт или попытка слушания",
    ],
    examples: [
      "Did you *listen* to the weather forecast this morning?.    Please *listen* carefully",
      "You should *listen* to your doctor's advice.",
      "We need to have a *listen* to the customer's feedback before making changes.",
    ],
  },
  {
    headword: "hand",
    PoS: "n, v",
    IPA: "[hænd]",
    definitions: [
      "_n_ рука",
      "_n_ помощь в выполнении работы",
      "_n_ работник, особенно выполняющий физический труд",
      '_n_ (часто в составе "hour hand", "minute hand" и т.п.) тонкий указатель на циферблате часов, который движется, чтобы показывать время',
      "_v_ передавать",
    ],
    examples: [
      "He raised his *hand*.",
      "Could you give me a *hand* with these boxes?",
      "The farm hired extra *hands* during the harvest season.    As a young deck *hand*, he learned everything about sailing.",
      "The big *hand* on the clock points to the minutes.",
      "Could you *hand* me that pen?",
    ],
  },
  {
    headword: "stay",
    PoS: "v, n",
    IPA: "[steɪ]",
    definitions: [
      "_v_ оставаться в одном месте или состоянии",
      "_n_ период времени, проведённый где-либо",
      "_v_ (формально, юр.) приостанавливать, откладывать или временно прекращать действие (обычно судебное решение или процесс)",
      "_n_ опора, поддержка – например канат, столб или распорка",
    ],
    examples: [
      "I'll *stay* a little longer.    Try to *stay* calm during the emergency.",
      "I enjoyed my week-long *stay* in Paris.",
      "The government decided to *stay* the implementation of the new regulation until further review.",
      "Before the earthquake, extra diagonal *stays* were added to the bridge.",
    ],
  },
  {
    headword: "bring",
    PoS: "v",
    IPA: "[bɹɪŋ]",
    definitions: [
      "_v_ перемещать что-то или кого-то к некоторому месту",
      "_v_ вызывать, быть причиной появления чего-то",
    ],
    examples: [
      "Can you *bring* your laptop?",
      "The rain *brought* relief from the heat.",
    ],
  },
  {
    headword: "change",
    PoS: "v, n",
    IPA: "[tʃeɪndʒ]",
    definitions: [
      "_v_ менять – делать или становиться другим",
      "_n_ изменение – состояние или событие становления другим",
      "_v_ обменивать одну вещь на другую или деньги одного вида на другой",
      "_n_ оставшиеся деньги после оплаты",
      "_n_ мелкие монеты",
    ],
    examples: [
      "Let's *change* the subject.    He decided to *change* his job after ten years.",
      "There was a big *change* in schedule.",
      "Can you *change* this $20 bill for two tens?",
      "Here is your *change* after paying for the coffee.",
      "I need some small *change* for the vending machine.",
    ],
  },
  {
    headword: "turn",
    PoS: "v, n",
    IPA: "[tɜɹn]",
    definitions: [
      "_v_ поворачивать(ся) – двигаться или заставлять двигаться по кругу или вокруг оси",
      "_v_ менять направление движения или взгляда",
      "_v_ становиться или преобразовываться во что-либо",
      "_n_ действие вращения или поворота",
      "очередь – возможность что-то сделать в определённой последовательности",
    ],
    examples: [
      "The wheels began to *turn* slowly.",
      "*Turn* left at the corner.",
      "The leaves *turned* yellow in the fall.",
      "The path follows the river with a gentle *turn* to the east.    To open the safe, you must complete four specific *turns* of the dial.",
      "It's your *turn* now.    It's your *turn* to roll the dice.",
    ],
  },
  {
    headword: "another",
    PoS: "det, pron",
    IPA: "[əˈnʌðəɹ]",
    definitions: [
      "_det, pron_ один дополнительный",
      "_det, pron_ другой, отличный от уже упомянутого",
    ],
    examples: [
      "Would you like *another* (cup of tea)?",
      "Let's try *another* (option).    This approach didn't work, so we need to try *another* (one).",
    ],
  },
  {
    headword: "child",
    PoS: "n",
    IPA: "[tʃaɪld]",
    definitions: [
      "_n_ человек, кто еще не взрослый",
      "_n_ сын или дочь независимо от возраста",
    ],
    examples: [
      "The *child* asked a question.",
      "She is the youngest *child* in the family.",
    ],
  },
  {
    headword: "hold",
    PoS: "v, n",
    IPA: "[hoʊld]",
    definitions: [
      "_v_ держать – удерживать что-либо в руках или с помощью другой части тела, или поддерживать в определённом положении",
      "_n_ действие или манера держания",
      "_v_ сохранять состояние",
      "_v_ вмещать, удерживать, быть достаточным для",
      "_v_ проводить мероприятие",
    ],
    examples: [
      "He was standing on the stage, *holding* the microphone close to his mouth.    Please *hold* the door.",
      "The tool provides a strong magnetic *hold* on small screws.",
      "The price of gold is expected to *hold* at this level for the next few weeks.    The contract will *hold* good for another two years.",
      "The maximum weight this luggage rack can *hold* is 50 kilograms.",
      "They will *hold* a meeting tomorrow morning.",
    ],
  },
  {
    headword: "father",
    PoS: "n",
    IPA: "[ˈfɑðəɹ]",
    definitions: ["_n_ отец – родитель мужского пола"],
    examples: ["He took over the family business from his *father*."],
  },
  {
    headword: "mother",
    PoS: "n",
    IPA: "[ˈmʌðəɹ]",
    definitions: [
      "_n_ мать – родитель женского пола",
      "_v_ заботиться о ком-то по-матерински",
    ],
    examples: [
      "My *mother* loves reading.",
      "She always *mothers* her younger siblings.",
    ],
  },
  {
    headword: "many",
    PoS: "det, pron, n, adj",
    IPA: "[ˈmɛni]",
    definitions: [
      "_det_ много",
      "_pron_ многие",
      "_n_ большое количество людей; большинство",
      "_adj_ многочисленный",
    ],
    examples: [
      "*Many* people were there.",
      "Of the available options, *many* are too expensive for our budget.",
      "She knew she had to appeal to the *many*, not just the experts.",
      "The reasons for his sudden departure are *many* and varied.    She was overwhelmed because the choices presented were so *many*.",
    ],
  },
  {
    headword: "world",
    PoS: "n",
    IPA: "[wɜɹld]",
    definitions: [
      "_n_ планета Земля и все вещи и люди на ней",
      "_n_ отдельная область, сфера интересов или группа людей",
    ],
    examples: [
      "The *world* is changing fast.    Traveling the *world* is her biggest dream.",
      "He spends most of his time in the academic *world*.",
    ],
  },
  {
    headword: "same",
    PoS: "adj, pron",
    IPA: "[seɪm]",
    definitions: [
      "_adj_ такой же, тот же самый",
      "the same adv: одинаково, тем же образом",
      "_pron_ то же самое",
    ],
    examples: [
      "We have the *same* position.    They wore *the same* uniform to the competition.",
      "The two robots are programmed to work *the same*, following identical procedures.",
      "The professor gave extra time to one student, and others demanded the *same*.",
    ],
  },
  {
    headword: "minute",
    PoS: "n, adj",
    IPA: "[ˈmɪnɪt; adj maɪˈnut]",
    definitions: [
      "_n_ минута",
      "_n_ очень короткий промежуток времени",
      "_n_ <в основном во множественном числе, minutes> официальный протокол собрания или встречи",
      "_n_ определённый момент времени",
      "_adj_ чрезвычайно маленький, мельчайший",
    ],
    examples: [
      "The meeting lasted for twenty *minutes*.",
      "Wait a *minute*.    I'll be with you in a *minute*.",
      "Please read the *minutes* from the last session.",
      "He left the room the *minute* the presentation finished.",
      "There was only a *minute* chance of the two companies merging.    Even the most *minute* vibration can disrupt the laser alignment.",
    ],
  },
  {
    headword: "lose",
    PoS: "v",
    IPA: "[luz]",
    definitions: [
      "_v_ терять",
      "_v_ терпеть поражение, проигрывать",
      "_v_ лишаться, утрачивать",
      "_v_ тратить впустую",
    ],
    examples: [
      "Don't *lose* your keys.    I don't want to *lose* my way in this unfamiliar part of the city.",
      "Our team *lost* the final game 3-0.    Despite having strong evidence, the lawyer ended up *losing* the case.",
      "She managed to *lose* ten pounds on the new diet.",
      "If we delay the project any further, we will *lose* valuable time.",
    ],
  },
  {
    headword: "money",
    PoS: "n",
    IPA: "[ˈmʌni]",
    definitions: [
      "_n_ деньги",
      "on the money: совершенно верно; абсолютно точно",
    ],
    examples: [
      "We need to save *money*.",
      "Her forecast for the stock market last quarter was absolutely *on the money*.",
    ],
  },
];
